name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push aws-eks
        uses: docker/build-push-action@v3
        with:
          context: ./aws-eks
          platforms: linux/amd64,linux/arm64
          build-args: |
            KUBECTL_VERSION=1.24.4
            TERRAFORM_VERSION=1.3.4
            HELM_VERSION=3.10.2
            KUSTOMIZE_VERSION=4.5.7
            KUBESEAL_VERSION=0.19.1
            KUBERNETES_SIGS_VERSION=0.5.9
          push: true
          tags: |
            terraformaws/eks:latest
            terraformaws/eks:1.23