name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push aws-eks
        uses: docker/build-push-action@v3
        with:
          context: ./aws-eks
          platforms: linux/amd64,linux/arm64
          build-args: |
            KUBECTL_VERSION=1.32.2
            TERRAFORM_VERSION=1.9.8
            HELM_VERSION=3.17.0
            KUSTOMIZE_VERSION=5.5.0
            KUBESEAL_VERSION=0.28.0
            KUBERNETES_SIGS_VERSION=0.6.30
          push: true
          tags: |
            terraformaws/eks:latest
            terraformaws/eks:1.32
